@debug ||= false
@configure_aws ||= false
@create_terraform_variables ||= true
@kill_all_ruby_processes ||= false
@add_swap_memory ||= true
@code_directory ||= "/root/code"
@app_name ||= "development-machine"
@working_directory ||= "#{@code_directory}/#{@app_name}"
@github_repo ||= "mhamouda1/development-machine"
@recommended_linux ||= "CentOS Linux release 7.6.1810"
@installations ||= ["tmux", "vim", "docker", "docker-compose", "terraform", "ag"]
@scripts_dir ||= "my_scripts"
